### ISSUE TITLE
As a user I want to be able to format my messages using markdown

### ISSUE THREAD

**Issue by mbcarterdev** [asyncApes/clack#21]
As a user I want to be able to format my messages, ie bold, italic, font change, code snippet, etc so that my messages can be more readable and better reflect the tone/intent of my communication.

**Comment by peterschussheim** [comment]
- convert text emoji ( :) ) to display emoji icon
- github MD api?

**Comment by xutopia** [comment]
* Need an indicator to mark the beginning/end of MD
* Need to parse the user input to accommodate for regular and MD message
* https://github.com/rexxars/react-markdown
