### ISSUE TITLE
As a user, I would like to send a private message to another user connected to the app

### ISSUE THREAD

**Issue by xutopia** [asyncApes/clack#33]
As a user I want to be able to send private messages with any other user in the app so I can communicate privately

**Comment by peterschussheim** [comment]
- [ ] Add listener on server (`io.on('private message', (toUser, fromUsername, text`) [SERVER]
- [ ] Channel management handlers (creation, `setCurrentChannel`) [SERVER]
- [ ] Add a check on server that verifies the message recipient exists [SERVER]
   - [ ] Add emitter on server (`emit('handle private message', fromUsername, text`) [SERVER]

- [ ] Channel creation [CLIENT]
   - [ ] action [CLIENT]
   - [ ] reducer [CLIENT]
   - [ ] saga [CLIENT]
   - [ ] initial state [CLIENT]
- [ ] Change channel (setCurrentChannel) [CLIENT]
- [ ] `handleClickOnUser()` [CLIENT]
- [ ] `handleSendDirectMessage()`[CLIENT]
- [ ] create modal or popup that appears when clicking on username [CLIENT]
   - [ ] provide button that user clicks on to load private conversation [CLIENT]
      - [ ] load reusable Room component [CLIENT]

**Comment by xutopia** [comment]
For `create modal or popup...` Does this mean that private messaging will be done in popups/modals instead of a "room"?

**Comment by peterschussheim** [comment]
I was thinking that on clicking a username in sidebar, a popup loads containing a button "Private Message".  On clicking this button, we set the currentRoom to the "private channel".
