### ISSUE TITLE
As a user, I would like to see a list of users currently in the channel

### ISSUE THREAD

**Issue by peterschussheim** [asyncApes/clack#47]

**Comment by mbcarterdev** [comment]
user/fetch route added, built Sidebar component as of 2/16/17 7pm, need code review and touchups, not sure what else is needed

**Comment by mbcarterdev** [comment]
need to add fetchusers function file in the actions folder

**Comment by mbcarterdev** [comment]
need to test the component

**Comment by mbcarterdev** [comment]
Directory component added with hard-coded userlist rendering on page, waiting on usernames array in initial state
