### ISSUE TITLE
As the App, I would like to persist data server-side in a relational database

### ISSUE THREAD

**Issue by peterschussheim** [asyncApes/clack#50]

**Comment by peterschussheim** [comment]
- server side controllers
- server side models
- user schema
- message schema
- env variables
- testing

**Comment by mbcarterdev** [comment]
as of 2/10 7:45pm, schema are done, env vars are set, need to collaborate on controllers and models

**Comment by mbcarterdev** [comment]
preliminary messages model is done, probably everything for mvp is done.
